### ISSUE TITLE
New design and flow: UI/UX Feedback & Questions

### ISSUE THREAD

**Issue by bhryck** [hmcc-global/hmcchk-web#849]
devs please compile your questions and feedbacks in the comment

Don't have to follow but possible/suggested structure to give some feedback: 
1. Are the proposed components and the way we use them to display information helpful? Like carousel/slide for story
2. Are there different ways that we should organize certain elements
3. Any other detailed wording/changes

**Comment by Midnite1212** [comment]
just wanna clarify, now when we go to rippleout page, we have a landing page that has all the sections. So I assume in the design our landing page would be the story?

**Comment by bhryck** [comment]
1. this is a really cool feature, makes the page more interactive, but I can see how it is confusing for mobile users.

![Image](https://github.com/hmcc-global/hmcchk-web/assets/24607458/3baf759f-c532-4d43-adee-496e457024ce)


2. I feel like we can also put the "ways to give" on the top of the "plan ahead" because we may want to highlight that giving must be made with the "RIPPLE OUT" comment to count. but Ill leave it to CXO to make the decission

![Image](https://github.com/hmcc-global/hmcchk-web/assets/24607458/152548a3-7163-489c-8bd1-2f52a8717961)

3. think this is an ET decision but I feel like this section could be good to really highlight the use of our space. we can add more detail about the uses of each room.

![Image](https://github.com/hmcc-global/hmcchk-web/assets/24607458/ef7cea03-5a9d-4a21-a220-6ac0d42ad77b)

**Comment by tamarayustian** [comment]
- what happens when we click this button 'i want to participate'? goes to google form? or a modal pop up with info? or what
![Screenshot_2023-10-21-14-45-52-53_8ee8015dd2b473d44c46c2d8d6942cec.jpg](https://github.com/hmcc-global/hmcchk-web/assets/26876443/fa5c9624-b060-472f-9c6c-795c9e825bc4)

- is this confirmed gif? i remember cxo asked me through phone call if it can be scroll animation
![Screenshot_2023-10-21-14-48-12-37_8ee8015dd2b473d44c46c2d8d6942cec.jpg](https://github.com/hmcc-global/hmcchk-web/assets/26876443/a4830c68-35ea-4ec0-ab42-132208fdeed2)
